# Header
menu:
  Home: /
  Archives: /archives
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts

# 自定义颜色
color:
  theme_color: "#00BDAA" #主题颜色，将应用大都数位置
  theme_second_color: "#F1E7B6" #辅助颜色
  theme_highlight_color: "#FE346E" #高亮颜色
  nav_color: "#fff" #顶部导航栏的颜色
  bg_color: "#EEEEEE" #背景颜色
  foot_color: "#00BDAA" #底部背景颜色
  foot_text_color: "#fff" #底部文字颜色
  a_color: #超链接的颜色
  a_hover_color: #当鼠标移动到超链接时的样式
  widget_bg_color: "#ffff" #widget的背景颜色
  code_bg_color: #小代码块的背景颜色
  code_text_color: #小代码块的文字颜色

# 网站个性化
icon_img: img/icon03.png #标签页图标
banner_img: ../img/bg.jpg #网站顶端图片
site_author: 任我行
site_name: 任我行的小站

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: false

# Miscellaneous
google_analytics:
gauges_analytics:
twitter:
google_plus:
fb_admins:
fb_app_id:
