
# main menu navigation
menu:
  ä¸»é¡µ: /
  å½’æ¡£: /archives
  å…³äº: /about

# å¤´åƒä»¥åŠå›¾æ ‡çš„è·¯å¾„
me: 
  autor: ä»»æˆ‘è¡Œ
  subtitile: åŠ æ²¹ğŸ˜¸
  avator: img/avator.jpg
  icon: img/icon.png

# å‹æƒ…è¿æ¥
link:
  github: https://github.com/FuShaoLei
  email: 1563250958@qq.com

